DoAnWeb/Controllers/BradController.cs
using DoAnWeb.Models;
using DoAnWeb.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoAnWeb.Controllers
{

    public class BradController : Controller
    {
        private readonly DataContext _dataContext;
        public BradController(DataContext context)
        {
            _dataContext = context;
        }
        public async Task<IActionResult> Index(string Slug = "")
        {
            BradModel bard = _dataContext.Brands.Where(c => c.Slug == Slug).FirstOrDefault();
            if (bard == null) { return RedirectToAction("Index"); }
            var productByBard = _dataContext.Products.Where(p => p.Brad.Id == bard.Id);
            // FirstOrDefault ra 1 gia tri, ma orderby ra 1 mang :v, di nhien nos wtf r ok :v
            return View(await productByBard.OrderByDescending(p => p.Id).ToListAsync());
        }
    }
}

DoAnWeb/Controllers/CategoryController.cs
using DoAnWeb.Models;
using DoAnWeb.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoAnWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly DataContext _dataContext;
        public CategoryController(DataContext context)
        {
            _dataContext = context;
        }
        public async Task<IActionResult> Index(string Slug = "")
        {
            CategoryModel category = _dataContext.Categories.Where(c => c.Slug == Slug).FirstOrDefault();
            if (category == null) { return RedirectToAction("Index"); }
            var productByCategory = _dataContext.Products.Where(p => p.Category.Id == category.Id);
            // FirstOrDefault ra 1 gia tri, ma orderby ra 1 mang :v, di nhien nos wtf r ok :v
            return View(await productByCategory.OrderByDescending(p => p.Id).ToListAsync());
        }
    }
}

DoAnWeb/Controllers/CheckoutController.cs
using DoAnWeb.Models;
using DoAnWeb.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System;
using System.Threading.Tasks;
using DoAnWeb.Models.Repository.Compoments;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace DoAnWeb.Controllers;

[Authorize]
public class CheckoutController : Controller
{
    private readonly DataContext _dataContext;

    public CheckoutController(DataContext context)
    {
        _dataContext = context;
    }

    public IActionResult Index()
    {
        var userEmail = User.FindFirstValue(ClaimTypes.Email);

        var orders = _dataContext.Orders.Where(o => o.UserName == userEmail)
            .Include(o => o.OrderDetails)
            .Include("OrderDetails.Product")
            .OrderByDescending(o => o.CreatedDate)
            .ToList();

        return View(orders);
    }

    public async Task<IActionResult> Checkout()
    {
        List<CartItemModel> cartItems = HttpContext.Session.GetJson<List<CartItemModel>>("Cart") ?? new List<CartItemModel>();

        var userEmail = User.FindFirstValue(ClaimTypes.Email);
        if (userEmail == null)
        {
            return RedirectToAction("Login", "Account");
        }

        var ordercode = Guid.NewGuid().ToString();

        var orderItem = new OrderModel
        {
            OrderCode = ordercode,
            UserName = userEmail,
            Status = 1,
            CreatedDate = DateTime.Now,
            
        };

        List<OrderDetails> orderDetails = cartItems.Select(i =>
        {
            var product = _dataContext.Products.Find(i.ProductId);

            var od = new OrderDetails() { };
            od.Product = product;
            od.Order = orderItem;
            od.Price = i.Price;
            od.Quanlity = i.Quantity;
            return od;
        }).ToList();


        orderItem.OrderDetails = orderDetails;

        _dataContext.Add(orderItem);
        await _dataContext.SaveChangesAsync();
        
        HttpContext.Session.SetJson("Cart", new List<object>());

        TempData["success"] = "Đơn hàng đã được tạo";
            
        return RedirectToAction("Index");
    }
}

DoAnWeb/Controllers/ProductController.cs
using DoAnWeb.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoAnWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly DataContext _dataContext;
        public ProductController(DataContext context)
        {
            _dataContext = context;

		}
        public IActionResult Index(string search)
        {
            if (string.IsNullOrEmpty(search))
            {
                return LocalRedirect("/");
            }
            ViewBag.Search = search;
			var products = _dataContext.Products.Where(p => p.Name.ToLower().Contains(search.ToLower()))
                .Include(p=>p.Brad)
                .Include(p => p.Category)
                .ToList();
			return View(products);
        }
        public async Task<IActionResult> Details(int Id)
        {
            if (Id == null)
            {
                return RedirectToAction("Index");
            }


			var productByCategory = _dataContext.Products.Where(p => p.Id == Id)
                .Include(p => p.Category).FirstOrDefault();

            var recommended = _dataContext.Products.Include(p => p.Category)
                .Where(p => p.Category == productByCategory.Category).ToList();
            ViewBag.Recommended = recommended;

            return View(productByCategory);
        }
    }
}

DoAnWeb/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head>
<!--/head-->

<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="btn-group pull-right">
                            
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                @if (User.Identity?.IsAuthenticated ?? false)
                                {
                                    <li><a href="/Account/Logout"><i class="fa fa-lock"></i>Hi, @User.Identity.Name, Logout</a></li>
                                }
                                else
                                {
                                    <li><a asp-controller="Account" asp-action="Login"><i class="fa fa-lock"></i>Login</a></li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="/" class="active">Home</a></li>
                                <li class="dropdown">
                                    <a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a asp-action="Index" asp-controller="Product">Product </a></li>
                                        <li><a asp-action="Index" asp-controller="Category">Categories</a></li>
                                        <li><a asp-action="Index" asp-controller="Brad">Brand</a></li>
                                        <li><a asp-action="Index" asp-controller="Checkout">Checkout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/header-bottom-->
    </header>
    <!--/header-->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-10">
                    @Html.Partial("_NotificationPartial")
                </div>
                <div class="col-sm-12">
                    @RenderBody();
                </div>
            </div>
        </div>
    </section>

    <footer id="footer">
        <!--Footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2024 E-SHOPPER Inc. All rights reserved.</p>
                    <p class="pull-right">Designed by <span>Neptune</span></p>
                </div>
            </div>
        </div>
    </footer>
    <!--/Footer-->

    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/price-range.js"></script>
    <script src="~/js/jquery.prettyPhoto.js"></script>
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

DoAnWeb/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
	<div class="alert alert-success notification">@TempData["success"]</div>
}

@if (TempData["error"] != null)
{
	<div class="alert alert-danger notification">@TempData["error"]</div>
}

DoAnWeb/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="left-sidebar">
	<h2>Category</h2>
	<div class="panel-group category-products" id="accordian">

		<vc:categories></vc:categories>
		
	</div><!--/category-products-->

	<div class="brands_products">
		<!--brands_products-->
		<h2>Brands</h2>
		<div class="panel-group category-products" id="accordian">

		<vc:brads></vc:brads>
		</div><!--/category-products-->
	</div><!--/brands_products-->
</div>
</div>